### ISSUE TITLE
External file conversion of ignore list

### ISSUE THREAD

**Issue by TAKEDA-Takashi** [textlint/textlint-filter-rule-whitelist#2]
Currently I write an ignore list inline in .textlintrc file.
I want to make an ignore list an external file so that it can be read.

I think it is convenient to write as follows.

```json
{
    "filters": {
        "whitelist": {
            "allow": [
                "ignored-word",
                "/\\d+/",
                "/^===/m"
            ],
            "allowPaths": [
                "./allow-words.yml"
            ]
        }
    }
}
```

**Comment by azu** [comment]
Thanks for suggestion.

I've implemented this feature. #3  and Realse [1.2.0](https://github.com/textlint/textlint-filter-rule-whitelist/releases/tag/1.2.0 "1.2.0").

```json
{
    "filters": {
        "whitelist": {
            "whitelistConfigPaths": [
                "./allow.json",
                "./allow.yml"
            ]
        }
    }
}
```

These files should be following formats.


`allow.json`:
```
[
  "allow",
  "/yes/i"
]
```    

`allow.yml`:
```
- "allow",
- /yes/i
```
